### ISSUE TITLE
Deprecate dev input on setup-python

### ISSUE THREAD

**Issue by ChrisLovering** [HassanAbouelela/actions#13]
The dev arg determines whether or not to add `--no-dev` to the poetry install args. This can be deprecated/removed now, since we support `install_args` which can specify this directly.

**Comment by HassanAbouelela** [comment]
Thanks, I'll mark it deprecated soon.

**Comment by HassanAbouelela** [comment]
Deprecated in v1.4.0, set to be removed in v2. You can find a migration guide here https://github.com/HassanAbouelela/actions/releases/tag/setup-python_v1.4.0
